attendance/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    #READ
    path("", views.index, name="index"),
    path("<str:groupId>/employees/", views.employees, name="employees"),
    path("<str:groupId>/profile/<str:employeeId>/<str:yearId>/<str:monthId>/", views.profile, name="profile"),

    # ADD
    path("addGroup/", views.addGroup, name="addGroup"),
    path("<str:groupId>/addEmployee/", views.addEmployee, name="addEmployee"),
    path("<str:groupId>/addYear/", views.addYear, name="addYear"),
    path("<str:groupId>/initMonth/", views.initMonth, name="initMonth"), 
    path("<str:groupId>/addMonth/<str:employeeId>/<str:yearId>/<str:monthId>/", views.addMonth, name="addMonth"),
    path("<str:groupId>/addDay/<str:employeeId>/<str:yearId>/<str:monthId>/", views.addDay, name="addDay"),

    # UPDATE
    path("updateGroup/<str:groupId>", views.updateGroup, name="updateGroup"),
    path("<str:groupId>/<str:employeeId>/updateEmployee/", views.updateEmployee, name="updateEmployee"),
    path("<str:groupId>/<str:yearId>/updateYear/<str:employeeId>/<str:currentYearId>/<str:currentMonthId>/", views.updateYear, name="updateYear"),
    path("<str:groupId>/<str:monthId>/updateMonth/<str:employeeId>/<str:currentYearId>/<str:currentMonthId>/", views.updateMonth, name="updateMonth"),
    path("<str:groupId>/<str:dayId>/updateDay/<str:employeeId>/<str:currentYearId>/<str:currentMonthId>/", views.updateDay, name="updateDay"),

    # DELETE
    path("deleteGroup/<str:groupId>", views.deleteGroup, name="deleteGroup"),
    path("<str:groupId>/<str:employeeId>/deleteEmployee/", views.deleteEmployee, name="deleteEmployee"),
    path("<str:groupId>/<str:yearId>/deleteYear/", views.deleteYear, name="deleteYear"),
    path("<str:groupId>/<str:monthId>/deleteMonth/", views.deleteMonth, name="deleteMonth"),
    path("<str:groupId>/<str:dayId>/deleteDay/<str:employeeId>/<str:currentYearId>/<str:currentMonthId>/", views.deleteDay, name="deleteDay"),
]

main/forms.py
from django.forms import ModelForm
from main.models import *

class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = "__all__"

class EmployeeForm(ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

class YearForm(ModelForm):
    class Meta:
        model = Year
        fields = "__all__"



class MonthForm(ModelForm):
    class Meta:
        model = Month
        fields = "__all__"



class DayForm(ModelForm):
    class Meta:
        model = Day
        fields = "__all__"

main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse

from .models import *
from .forms import *

# Create your views here.
def index(request):
    groups = Group.objects.all()

    context = {
        "groups": groups,
    }
    return render (request, "main/index.html", context)



def employees(request, groupId):
    media_path = request.build_absolute_uri("/media/")
    group = Group.objects.get(id=groupId)
    employees = group.employees.all()
            

    context = {
        "media_path": media_path,
        "group": group,
        "employees": employees,
    }
    return render(request, "main/pages/employees.html", context)



def profile(request, groupId, employeeId, yearId, monthId):
    group = Group.objects.get(id=groupId)
    employee = group.employees.get(id=employeeId)
    current_year = employee.years.get(id=yearId)
    current_month = current_year.months.get(id=monthId)
    employee_days = current_month.days.all()


    context = {
        "group": group,
        "employee": employee,
        "current_year": current_year,
        "current_month": current_month,
        "employee_days": employee_days,
    }
    return render(request, "main/pages/profile.html", context)

 

#  ---------------------------------------- ADD ----------------------------------------
def addGroup(request):
    if request.method == "POST":
        form = GroupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("main:index")
        else:
            return redirect("main:index")
        

def addEmployee(request, groupId):
    if request.method == "POST":
        form = EmployeeForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("main:employees", groupId)
        else:
            print(form.errors)
            return redirect("main:index")


def addYear(request, groupId):
    if request.method == "POST":
        form = YearForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("main:employees", groupId)
        else:
            return redirect("main:index")
        


def addMonth(request, groupId, employeeId, yearId, monthId):
    if request.method == "POST":
        form = MonthForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("main:profile", groupId, employeeId, yearId, monthId)
        else:
            return redirect("main:index")
        


def addDay(request, groupId, employeeId, yearId, monthId):
    if request.method == "POST":
        form = DayForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("main:profile", groupId, employeeId, yearId, monthId)
        else:
            print(form.errors)
            return redirect("main:index")
            


def initMonth(request, groupId):
    if request.method == "POST":
        form = MonthForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("main:employees", groupId)
        else:
            return redirect("main:index")
        

#  ---------------------------------------- UPDATE ----------------------------------------
def updateGroup(request, groupId):
    if request.method == "POST":
        group = Group.objects.get(id=groupId)
        form = GroupForm(request.POST, instance=group)

        if form.is_valid():
            form.save()
            return redirect("main:index")
        else:
            return redirect("main:index")
        
        
        
def updateEmployee(request, groupId, employeeId):
    if request.method == "POST":
        employee = Employee.objects.get(id=employeeId)
        form = EmployeeForm(request.POST, request.FILES, instance=employee)

        if form.is_valid():
            form.save()
            return redirect("main:employees", groupId)
        else:
            print(form.errors)
            return redirect("main:index")
        


def updateYear(request, groupId, yearId, employeeId, currentYearId, currentMonthId):
    if request.method == "POST":
        year = Year.objects.get(id=yearId)
        form = YearForm(request.POST, instance=year)

        if form.is_valid():
            form.save()
            return redirect("main:profile", groupId, employeeId, currentYearId, currentMonthId)
        else:
            return redirect("main:index")
        


def updateMonth(request, groupId, monthId, employeeId, currentYearId, currentMonthId):
    if request.method == "POST":
        month = Month.objects.get(id=monthId)
        form = MonthForm(request.POST, instance=month)

        if form.is_valid():
            form.save()
            return redirect("main:profile", groupId, employeeId, currentYearId, currentMonthId)
        else:
            return redirect("main:index")
        


def updateDay(request, groupId, dayId, employeeId, currentYearId, currentMonthId):
    if request.method == "POST":
        day = Day.objects.get(id=dayId)
        form = DayForm(request.POST, instance=day)

        if form.is_valid():
            form.save()
            return redirect("main:profile", groupId, employeeId, currentYearId, currentMonthId)
        else:
            return redirect("main:index")
        

#  ---------------------------------------- DELETE ----------------------------------------
def deleteGroup(request, groupId):
    if request.method == "POST":
        group = Group.objects.get(id=groupId)
        group.delete()
        return redirect("main:index")
    


def deleteEmployee(request, groupId, employeeId):
    if request.method == "POST":
        employee = Employee.objects.get(id=employeeId)
        employee.delete()
        return redirect("main:employees", groupId)
    


def deleteYear(request, groupId, yearId):
    if request.method == "POST":
        year = Year.objects.get(id=yearId)
        year.delete()
        return redirect("main:employees", groupId)
    
    
def deleteMonth(request, groupId, monthId):
    if request.method == "POST":
        month = Month.objects.get(id=monthId)
        month.delete()
        return redirect("main:employees", groupId)
    

def deleteDay(request, groupId, dayId, employeeId, currentYearId, currentMonthId):
    if request.method == "POST":
        day = Day.objects.get(id=dayId)
        day.delete()
        return redirect("main:profile", groupId, employeeId, currentYearId, currentMonthId)

main/templates/main/index.html
{% extends "main/layout.html" %}

{% block body %}
<div x-data="{ modalOpen: false }">
    <button 
        @click="modalOpen = true;$nextTick(() => { $refs.input.focus(); })"
        onclick="addGroup()"
        class="bg-orange-400 flex items-center rounded py-3 px-5 font-semibold text-white hover:bg-opacity-75 transition-all"
    >
        إضافة نظام
        <span class="pr-2">
            <svg  class="fill-current font-bold" width="20" height="20" viewBox="0 0 24 24" focusable="false"><path d="M20 13h-7v7h-2v-7H4v-2h7V4h2v7h7v2z"></path></svg>
        </span>
    </button>
    <div class="flex py-5 min-h-full flex-wrap items-start justify-center gap-5">
        {% for group in groups %}
        <div 
            x-data="{ optionsOpen: false}"
            title="{{ group.title }}"
            class="flex flex-col bg-white items-center justify-center p-10 px-16 relative rounded-lg shadow-md"
        >
            <h1 class="text-xl font-bold">
                {{ group.title }}
            </h1>
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1" viewBox="0 0 48 48" enable-background="new 0 0 48 48" height="7rem" width="7rem" xmlns="http://www.w3.org/2000/svg">
                <circle fill="#FFA726" cx="12" cy="21" r="5"></circle>
                <g fill="#455A64">
                    <path d="M2,34.7c0,0,2.8-6.3,10-6.3s10,6.3,10,6.3V38H2V34.7z"></path>
                    <path d="M46,34.7c0,0-2.8-6.3-10-6.3s-10,6.3-10,6.3V38h20V34.7z"></path>
                </g>
                <circle fill="#FFB74D" cx="24" cy="17" r="6"></circle>
                <path fill="#607D8B" d="M36,34.1c0,0-3.3-7.5-12-7.5s-12,7.5-12,7.5V38h24V34.1z"></path>
                <circle fill="#FFA726" cx="36" cy="21" r="5"></circle>
                <circle fill="#FFA726" cx="12" cy="21" r="5"></circle>
                <circle fill="#FFA726" cx="36" cy="21" r="5"></circle>
            </svg>
            <a href="{% url 'main:employees' group.id %}">
                <button class="bg-orange-400 py-3 px-8 mt-4 text-white rounded text-sm font-semibold hover:bg-opacity-75 transition-all">دخول</button>
            </a>

            <!-- Options button -->
            <div
                @click.outside="optionsOpen = false"
                @click="optionsOpen = !optionsOpen"
                class="text-orange-400 absolute top-0 py-3 px-1 cursor-pointer left-0"
            >
                <div class="rounded-full transition-all hover:bg-gray-100">
                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="2rem" width="2rem" xmlns="http://www.w3.org/2000/svg">
                        <path d="M12 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0-6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 12c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z"></path>
                    </svg>
                </div>
            </div>

            <!-- Options menu -->
            <div 
                x-show="optionsOpen"
                x-transition:enter-start="opacity-0"
                x-transition:enter-end="opacity-100"
                x-transition:leave-start="opacity-100"
                x-transition:leave-end="opacity-0"
                :class="optionsOpen ? 'mt-5' : 'mt-0' "
                class="absolute top-7 z-10 mt-2 -left-7 rounded border bg-white transition-all"
            >
                    <div 
                        @click="modalOpen = true;$nextTick(() => { $refs.input.focus(); })"
                        onclick=
                            "updateGroup(
                                    '{{ group.title }}', 
                                    '{{ group.required_hours }}', 
                                    '{{ group.required_minutes }}',
                                    '{% url 'main:updateGroup' group.id %}'
                            )"
                        class="flex items-center justify-start gap-x-2 px-4 py-2 cursor-pointer hover:bg-gray-100"
                    >
                        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1.5rem" width="1.5rem" xmlns="http://www.w3.org/2000/svg"><path d="M4 21a1 1 0 0 0 .24 0l4-1a1 1 0 0 0 .47-.26L21 7.41a2 2 0 0 0 0-2.82L19.42 3a2 2 0 0 0-2.83 0L4.3 15.29a1.06 1.06 0 0 0-.27.47l-1 4A1 1 0 0 0 3.76 21 1 1 0 0 0 4 21zM18 4.41 19.59 6 18 7.59 16.42 6zM5.91 16.51 15 7.41 16.59 9l-9.1 9.1-2.11.52z"></path></svg>
                        <span>تعديل</span>
                    </div>
                    <div 
                        @click="modalOpen = true;$nextTick(() => { $refs.input.focus(); })"
                        onclick="deleteGroup('{% url 'main:deleteGroup' group.id %}')"
                        class="flex items-center gap-x-2 px-4 text-red-400 py-2 cursor-pointer hover:bg-gray-100"
                    >
                        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="1.5rem" width="1.5rem" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0V0z"></path><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM8 9h8v10H8V9zm7.5-5l-1-1h-5l-1 1H5v2h14V4z"></path></svg>
                        <span>حــذف</span>
                    </div>
            </div>
        </div>
        {% empty %}
            لا توجد بيانات.
        {% endfor %}
    
        <!-- Modal -->
        {% include "main/components/Modal.html" %}
    </div>
</div>

<script>
    const modal = document.getElementById("modal")

    function addGroup(){
        modal.innerHTML = 
        `<h3 class="pb-2 mb-3 text-xl font-bold sm:text-2xl">
            إضافة نظام جديد
        </h3>

        <form class="flex flex-col gap-y-3" action={% url 'main:addGroup' %} method="POST">
            {% csrf_token %}
            <input
                class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring" 
                type="text" 
                placeholder="أدخل اسم النظام، نظام 4 ساعات مثلا" 
                required=""
                x-ref="input"
                name="title"
                value=""
            >

            <div class="flex flex-col items-right justify-center gap-3">
                <p class="font-semibold">الوقت المطلوب:</p>
                <div class="flex justify-center items-center gap-x-3">
                    <input
                        class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring" 
                        placeholder="الساعات المطلوبة" 
                        required=""
                        name="required_hours"
                    >
                    <input
                        class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring" 
                        placeholder="الدقائق المطلوبة" 
                        required=""
                        name="required_minutes"
                    >
                </div>
                
            </div>

            <div class="flex flex-wrap justify-center mt-3 -mx-3">
                <div class="w-1/6 px-3">
                    <p
                        @click="modalOpen = false"
                        class="cursor-pointer block w-full p-3 text-base font-bold text-center text-white transition hover:bg-opacity-80 bg-red-600 border rounded-lg"
                    >
                        إلغاء
                    </p>
                </div>
                <div class="w-1/6 px-3">
                    <button
                        type="submit"
                        class="block w-full p-3 text-base font-bold text-center transition border rounded-lg hover:bg-opacity-80 bg-gray-100"
                    >
                        تم
                    </button>
                </div>
            </div>
        </form>`
    }

    function updateGroup(title, required_hours, required_minutes, url){
        modal.innerHTML = 
        `<h3 class="pb-2 mb-3 text-xl font-bold sm:text-2xl">
            تعديل معلومات النظام 
        </h3>

        <form class="flex flex-col gap-y-3" action="${url}" method="POST">
            {% csrf_token %}
            <input
                class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring" 
                type="text" 
                placeholder="أدخل اسم النظام، نظام 4 ساعات مثلا" 
                required=""
                x-ref="input"
                value="${title}"
                name="title"
            >

            <div class="flex flex-col items-right justify-center gap-3">
                <p class="font-semibold">الوقت المطلوب:</p>
                <div class="flex justify-center items-center gap-x-3">
                    <input
                        class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring" 
                        placeholder="الساعات المطلوبة" 
                        required=""
                        name="required_hours"
                        value="${required_hours}"
                    >
                    <input
                        class="w-full px-4 py-2 border rounded-md focus:outline-none focus:ring" 
                        placeholder="الدقائق المطلوبة" 
                        required=""
                        name="required_minutes"
                        value="${required_minutes}"
                    >
                </div>
                
            </div>

            <div class="flex flex-wrap justify-center mt-3 -mx-3">
                <div class="w-1/6 px-3">
                    <p
                        @click="modalOpen = false"
                        class="block w-full p-3 cursor-pointer text-base font-bold text-center text-white transition bg-red-600 border rounded-lg hover:bg-opacity-80"
                    >
                        إلغاء
                    </p>
                </div>
                <div class="w-1/6 px-3">
                    <button
                        type="submit"
                        class="block w-full p-3 text-base font-bold text-center transition border rounded-lg hover:bg-opacity-80 bg-gray-100"
                    >
                        تم
                    </button>
                </div>
            </div>
        </form>`
    }

    function deleteGroup(url){
        modal.innerHTML = 
        `<h3 class="pb-2 mb-3 text-xl font-bold sm:text-2xl">
            هل أنت متأكد؟
        </h3>

        <form class="flex flex-col gap-y-3" action="${url}" method="POST">
            {% csrf_token %}
            <div class="flex flex-wrap justify-center mt-3 -mx-3">
                <div class="w-1/6 px-3">
                    <p
                        @click="modalOpen = false"
                        class="block w-full p-3 cursor-pointer text-base font-bold text-center text-white transition bg-red-600 border rounded-lg hover:bg-opacity-80"
                    >
                        إلغاء
                    </p>
                </div>
                <div class="w-1/6 px-3">
                    <button
                        type="submit"
                        class="block w-full p-3 text-base font-bold text-center transition border rounded-lg hover:bg-opacity-80 bg-gray-100"
                    >
                        تم
                    </button>
                </div>
            </div>
        </form>`
    }
</script>
{% endblock %}

main/templates/main/layout.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>إدارة حضور وانصراف الموظفين</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    {% endcompress %}
</head>
<body class="font-kufi wrapper">

    
    <!-- Breadcrump -->          
    <div>
        <div class="flex items-center py-4 mx-auto overflow-x-auto whitespace-nowrap">
            <a href="{% url 'main:index' %}" class="text-orange-400 flex items-center text-orange-400 hover:bg-orange-400 hover:text-white rounded p-2 transition-all font-bold">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                </svg>

                <span class="mx-2">الرئيسية</span>
            </a>

            {% block breadcrump %}
            {% endblock %}

        </div>
    </div>

    {% block body %}
    {% endblock %}

    <script src="{% static 'js/alpine.js' %}"></script>
</body>
</html>